"""
Tests for GitHub Publisher module.
"""

import pytest
import subprocess
from pathlib import Path
from unittest.mock import Mock, patch, MagicMock
from datetime import datetime

from app.github.publisher import GitHubPublisher
from app.config import Settings


@pytest.fixture
def mock_settings():
    """Mock settings for testing."""
    settings = Settings(
        telegram_api_id="123",
        telegram_api_hash="test_hash",
        telegram_bot_token="test_bot_token",
        github_token="test_token",
        github_owner="test_owner",
        github_repo="test_repo",
        github_branch="main",
        channel_name="Test Channel",
        channel_username="@testchannel",
        channel_id="123456789",
        admin_user_ids="123456789",
        collection_interval_minutes=30,
        first_run_message_limit=5000,
        database_path=":memory:",
        telegram_session_name="test_session",
        output_dir="test_output",
        dry_run=False,
        log_level="INFO"
    )
    return settings


@pytest.fixture
def publisher(tmp_path, mock_settings):
    """Create a GitHub Publisher instance for testing."""
    with patch('app.github.publisher.get_settings', return_value=mock_settings):
        return GitHubPublisher(
            repo_url="https://github.com/test_owner/test_repo.git",
            branch="main",
            local_path=tmp_path / "github_repo",
            github_token="test_token"
        )


@pytest.fixture
def sample_output_dir(tmp_path):
    """Create a sample output directory with generated files."""
    output_dir = tmp_path / "output"
    output_dir.mkdir()
    
    # Create configs directory
    configs_dir = output_dir / "configs"
    configs_dir.mkdir()
    
    # Create sample config files
    (configs_dir / "all.txt").write_text("vmess://config1\nvless://config2\n")
    (configs_dir / "vmess.txt").write_text("vmess://config1\n")
    (configs_dir / "vless.txt").write_text("vless://config2\n")
    
    # Create metadata directory
    metadata_dir = output_dir / "metadata"
    metadata_dir.mkdir()
    
    # Create stats.json
    (metadata_dir / "stats.json").write_text('{"total_configs": 2}')
    
    # Create README.md
    (output_dir / "README.md").write_text("# Test Configs\n\nGenerated by V2Ray Aggregator")
    
    return output_dir


class TestGitHubPublisherInit:
    """Test GitHub Publisher initialization."""
    
    def test_init_with_all_params(self, tmp_path, mock_settings):
        """Test initialization with all parameters."""
        with patch('app.github.publisher.get_settings', return_value=mock_settings):
            publisher = GitHubPublisher(
                repo_url="https://github.com/owner/repo.git",
                branch="main",
                local_path=tmp_path / "repo",
                github_token="token123"
            )
            
            assert publisher.repo_url == "https://github.com/owner/repo.git"
            assert publisher.branch == "main"
            assert publisher.local_path == tmp_path / "repo"
            assert publisher.github_token == "token123"
    
    def test_init_with_settings(self, mock_settings):
        """Test initialization using settings."""
        with patch('app.github.publisher.get_settings', return_value=mock_settings):
            publisher = GitHubPublisher()
            
            assert publisher.repo_url == "https://github.com/test_owner/test_repo.git"
            assert publisher.github_token == "test_token"
    
    def test_build_repo_url(self, mock_settings):
        """Test building repository URL from settings."""
        with patch('app.github.publisher.get_settings', return_value=mock_settings):
            publisher = GitHubPublisher()
            url = publisher._build_repo_url(mock_settings)
            
            assert url == "https://github.com/test_owner/test_repo.git"
    
    def test_build_repo_url_missing_settings(self, mock_settings):
        """Test build_repo_url with missing settings."""
        mock_settings.github_owner = ""
        with patch('app.github.publisher.get_settings', return_value=mock_settings):
            with pytest.raises(ValueError, match="GITHUB_OWNER and GITHUB_REPO must be set"):
                GitHubPublisher()


class TestGitCommands:
    """Test Git command execution."""
    
    def test_run_git_command_success(self, publisher):
        """Test successful Git command execution."""
        with patch('subprocess.run') as mock_run:
            mock_run.return_value = MagicMock(stdout="success", stderr="")
            
            result = publisher._run_git_command(["git", "status"])
            
            assert result is not None
            mock_run.assert_called_once()
    
    def test_run_git_command_failure(self, publisher):
        """Test Git command failure handling."""
        with patch('subprocess.run') as mock_run:
            mock_run.side_effect = subprocess.CalledProcessError(1, "git", stderr="error")
            
            with pytest.raises(subprocess.CalledProcessError):
                publisher._run_git_command(["git", "invalid"])


class TestCloneRepository:
    """Test repository cloning operations."""
    
    def test_clone_new_repository(self, publisher):
        """Test cloning a new repository."""
        with patch.object(publisher, '_run_git_command') as mock_git:
            publisher._clone_repository()
            
            # Should call git clone
            calls = [call[0][0] for call in mock_git.call_args_list]
            assert any("clone" in call for call in calls)
    
    def test_clone_existing_repository(self, publisher):
        """Test updating an existing repository."""
        publisher.local_path.mkdir()
        
        with patch.object(publisher, '_run_git_command') as mock_git:
            publisher._clone_repository()
            
            # Should call git fetch and pull instead of clone
            calls = [call[0][0] for call in mock_git.call_args_list]
            assert any("fetch" in call for call in calls)
            assert any("pull" in call for call in calls)
            assert not any("clone" in call for call in calls)
    
    def test_clone_with_token(self, publisher):
        """Test cloning with authentication token."""
        with patch.object(publisher, '_run_git_command') as mock_git:
            publisher._clone_repository()
            
            # Check if token is used in URL
            calls = [call[0][0] for call in mock_git.call_args_list]
            clone_call = next(call for call in calls if "clone" in call)
            
            # Token should be in the URL
            assert publisher.github_token in str(clone_call)


class TestCopyFiles:
    """Test file copying operations."""
    
    def test_copy_files_to_repo(self, publisher, sample_output_dir):
        """Test copying generated files to repository."""
        publisher.local_path.mkdir()
        
        publisher._copy_files_to_repo(sample_output_dir)
        
        # Check if files were copied
        assert (publisher.local_path / "configs" / "all.txt").exists()
        assert (publisher.local_path / "configs" / "vmess.txt").exists()
        assert (publisher.local_path / "metadata" / "stats.json").exists()
        assert (publisher.local_path / "README.md").exists()
    
    def test_copy_files_creates_directories(self, publisher, sample_output_dir):
        """Test that target directories are created."""
        publisher.local_path.mkdir()
        
        publisher._copy_files_to_repo(sample_output_dir)
        
        assert (publisher.local_path / "configs").is_dir()
        assert (publisher.local_path / "metadata").is_dir()
    
    def test_copy_files_without_readme(self, publisher, sample_output_dir):
        """Test copying files when README doesn't exist."""
        publisher.local_path.mkdir()
        
        # Remove README
        (sample_output_dir / "README.md").unlink()
        
        publisher._copy_files_to_repo(sample_output_dir)
        
        # Other files should still be copied
        assert (publisher.local_path / "configs" / "all.txt").exists()
        # README should not exist
        assert not (publisher.local_path / "README.md").exists()


class TestCommitChanges:
    """Test Git commit operations."""
    
    def test_commit_changes(self, publisher):
        """Test committing changes."""
        with patch.object(publisher, '_run_git_command') as mock_git:
            mock_git.return_value = MagicMock(stdout="M file.txt\n", stderr="")
            
            publisher._commit_changes("Test commit")
            
            # Should call git add and git commit
            calls = [call[0][0] for call in mock_git.call_args_list]
            assert any("add" in call for call in calls)
            assert any("commit" in call for call in calls)
    
    def test_commit_no_changes(self, publisher):
        """Test committing when there are no changes."""
        with patch.object(publisher, '_run_git_command') as mock_git:
            mock_git.return_value = MagicMock(stdout="", stderr="")
            
            publisher._commit_changes("Test commit")
            
            # Should not call commit
            calls = [call[0][0] for call in mock_git.call_args_list]
            assert not any("commit" in call for call in calls)


class TestPushChanges:
    """Test Git push operations."""
    
    def test_push_changes(self, publisher):
        """Test pushing changes to remote."""
        with patch.object(publisher, '_run_git_command') as mock_git:
            publisher._push_changes()
            
            # Should call git push
            calls = [call[0][0] for call in mock_git.call_args_list]
            assert any("push" in call for call in calls)
    
    def test_push_configures_user(self, publisher):
        """Test that Git user is configured."""
        with patch.object(publisher, '_run_git_command') as mock_git:
            publisher._push_changes()
            
            # Should configure user email and name
            calls = [call[0][0] for call in mock_git.call_args_list]
            assert any("user.email" in str(call) for call in calls)
            assert any("user.name" in str(call) for call in calls)


class TestPublish:
    """Test complete publish workflow."""
    
    def test_publish_success(self, publisher, sample_output_dir):
        """Test successful publish workflow."""
        with patch.object(publisher, '_clone_repository'), \
             patch.object(publisher, '_copy_files_to_repo'), \
             patch.object(publisher, '_commit_changes'), \
             patch.object(publisher, '_push_changes'), \
             patch.object(publisher, '_run_git_command') as mock_git:
            
            mock_git.return_value = MagicMock(stdout="abc123", stderr="")
            
            result = publisher.publish(source_dir=sample_output_dir)
            
            assert result["success"] is True
            assert result["commit_hash"] == "abc123"
            assert result["error"] is None
    
    def test_publish_with_custom_message(self, publisher, sample_output_dir):
        """Test publish with custom commit message."""
        with patch.object(publisher, '_clone_repository'), \
             patch.object(publisher, '_copy_files_to_repo'), \
             patch.object(publisher, '_commit_changes') as mock_commit, \
             patch.object(publisher, '_push_changes'):
            
            publisher.publish(
                source_dir=sample_output_dir,
                commit_message="Custom message"
            )
            
            mock_commit.assert_called_once_with("Custom message")
    
    def test_publish_auto_message(self, publisher, sample_output_dir):
        """Test publish with auto-generated commit message."""
        with patch.object(publisher, '_clone_repository'), \
             patch.object(publisher, '_copy_files_to_repo'), \
             patch.object(publisher, '_commit_changes') as mock_commit, \
             patch.object(publisher, '_push_changes'):
            
            publisher.publish(source_dir=sample_output_dir)
            
            # Check that commit message contains timestamp
            call_args = mock_commit.call_args[0][0]
            assert "Update configs" in call_args
    
    def test_publish_git_error(self, publisher, sample_output_dir):
        """Test publish handling Git errors."""
        with patch.object(publisher, '_clone_repository') as mock_clone:
            mock_clone.side_effect = subprocess.CalledProcessError(1, "git", stderr="Auth failed")
            
            result = publisher.publish(source_dir=sample_output_dir)
            
            assert result["success"] is False
            assert result["error"] is not None
            assert "Git command failed" in result["error"]
    
    def test_publish_general_error(self, publisher, sample_output_dir):
        """Test publish handling general errors."""
        with patch.object(publisher, '_clone_repository') as mock_clone:
            mock_clone.side_effect = Exception("Unexpected error")
            
            result = publisher.publish(source_dir=sample_output_dir)
            
            assert result["success"] is False
            assert "Unexpected error" in result["error"]


class TestDryRun:
    """Test dry-run mode."""
    
    def test_dry_run_skip_publish(self, publisher, sample_output_dir):
        """Test that dry-run skips actual publishing."""
        publisher.dry_run = True
        
        with patch.object(publisher, '_clone_repository') as mock_clone:
            result = publisher.publish(source_dir=sample_output_dir)
            
            assert result["success"] is True
            assert result["error"] == "Skipped (dry run)"
            mock_clone.assert_not_called()


class TestCleanup:
    """Test cleanup operations."""
    
    def test_cleanup_removes_directory(self, publisher, tmp_path):
        """Test that cleanup removes local repository."""
        repo_path = tmp_path / "test_repo"
        repo_path.mkdir()
        publisher.local_path = repo_path
        
        publisher.cleanup()
        
        assert not repo_path.exists()
    
    def test_cleanup_nonexistent_directory(self, publisher):
        """Test cleanup when directory doesn't exist."""
        publisher.local_path = Path("nonexistent")
        
        # Should not raise error
        publisher.cleanup()
    
    def test_cleanup_error_handling(self, publisher, tmp_path):
        """Test cleanup error handling."""
        repo_path = tmp_path / "test_repo"
        repo_path.mkdir()
        publisher.local_path = repo_path
        
        with patch('shutil.rmtree') as mock_rmtree:
            mock_rmtree.side_effect = PermissionError("Access denied")
            
            # Should not raise error, just log warning
            publisher.cleanup()


class TestIntegration:
    """Integration tests for GitHub Publisher."""
    
    def test_full_publish_workflow(self, publisher, sample_output_dir):
        """Test complete publish workflow from start to finish."""
        publisher.local_path.mkdir(parents=True, exist_ok=True)
        with patch.object(publisher, '_run_git_command') as mock_git:
            # Mock git responses
            mock_git.return_value = MagicMock(stdout="abc123\nM file.txt\n", stderr="")
            
            result = publisher.publish(source_dir=sample_output_dir)
            
            assert result["success"] is True
            assert result["commit_hash"] == "abc123\nM file.txt"
    
    def test_publish_with_no_changes(self, publisher, sample_output_dir):
        """Test publish when there are no changes to commit."""
        publisher.local_path.mkdir(parents=True, exist_ok=True)
        with patch.object(publisher, '_clone_repository'), \
             patch.object(publisher, '_copy_files_to_repo'), \
             patch.object(publisher, '_commit_changes'), \
             patch.object(publisher, '_push_changes'), \
             patch.object(publisher, '_run_git_command') as mock_git:
            
            mock_git.return_value = MagicMock(stdout="abc123", stderr="")
            result = publisher.publish(source_dir=sample_output_dir)
            
            assert result["success"] is True
